import 'package:get/get.dart';

class ListingProvider extends GetxController {
//TODO: CREAR ANUNCIO
//TODO: MODIFICAR ANUNCIO
//TODO: ELIMINAR ANUNCIO
//TODO: ADD ANUNCIO TO FAVORITES
//TODO: DELETE ANUNCIO TO FAVORITES
//TODO: AÑADIR FOTOS AL ANUNCIO
//TODO: QUITAR FOTOS AL ANUNCIO

}
