import 'package:get/get.dart';

class UserProfileProvider extends GetxController {
//TODO: SERÁ EL MISMO PARA CUANDO SE CREE UN USUARIO QUE NO SEA DE GOOGLE Y PARA CUANDO SE MODIFICAN LOS DATOS DEL USER
//TODO: OBTENER DATOS DEL USUARIO
//TODO: ELIMINAR USUARIO
//TODO: OBTENER FAVORITOS DEL USUARIO FILTRADOS Y PAGINADOS
//TODO: OBTENER ANUNCIOS CREADOS POR EL USUARIO FILTRADOS Y PAGINADOS

}
